@startuml Widgets
scale 2
left to right direction
class Widget{
    + window
    + x
    + y
    + w
    + h
    + backgroundColor
    + __init__(window, x, y, w, h, backgroundColor)
    + draw()
    + update()
}

class Column{
    + Widgets
    + __init__(window, x, y, Widgets, maxHeight)
    + draw()
    + bottomPosition()
}

class Row{
    + Widgets
    + __init__(window, x, y, Widgets, maxWidth)
    + draw()
    + bottomPosition()
}

class UpdateWidget{
    + valuePointer
    + packetreader
    + __init__(window, x, y, w, h, backgroundColor, valuePointer, packetreader)
    + draw()
    + update()
}

class GearDisplay{
    + foregroundColor
    + padding
    + font
    + __init__(window, x, y, w, h, backgroundColor, foregroundColor, valuePointer, packetreader, padding)
    + draw()   
}

class HeaderBox{
    + foregroundColor
    + borderThickness
    + padding
    + fontSize
    + font
    + __init__(window, x, y, w, h, backgroundColor, foregroundColor, valuePointer, packetreader, borderThickness, padding, fontSize)
    + draw()   
}   

class Label{
    + foregroundColor
    + font
    + __init__(window, x, y, w, h, backgroundColor, foregroundColor, valuePointer, packetreader)
    + draw()    
}   

class OvertakeLabel{
    + foregroundColor
    + font
    + __init__(window, x, y, w, h, backgroundColor, foregroundColor, valuePointer, packetreader)
    + draw()    
}

class ProgressBar{
    + foregroundColor
    + __init__(window, x, y, w, h, backgroundColor, foregroundColor, valuePointer, packetreader)
    + draw()
}

Widget <|-- UpdateWidget
Widget <|-- Column
Widget <|-- Row
UpdateWidget <|-- GearDisplay
UpdateWidget <|-- HeaderBox
UpdateWidget <|-- Label
UpdateWidget <|-- OvertakeLabel
UpdateWidget <|-- ProgressBar


class Page{
    + window
    + widgetList: List<Widget>
    + __init__(window, widgetList)
    + addWidget(widget)
    + drawWidgets()
}

class SteeringWheelPage{
    + __init__(window)
    + build(pr)
}

Page <|-- SteeringWheelPage

@enduml